using System.Linq;
using Rosalind.Core;
using Rosalind.Core.Math;
using Xunit;

namespace Rosalind.Solutions {
    public class Solutions {
        private bool QuickEquivalent(double a, double b) {
            return QuickEquivalent(a, b, 0.001);
        }

        private bool QuickEquivalent(double a, double b, double maxRelativeError) {
            double fst, snd;
            if (a > b) {
                fst = a;
                snd = b;
            } else {
                fst = b;
                snd = a;
            }
            var error = (System.Math.Abs(fst - snd) / fst);
            return error <= maxRelativeError;
        }
        
        [Fact]
        public void DNA() {
            DNA_Solve("AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC", "20 12 17 21");
            DNA_Solve("TTAGGATATTAATTACGACGAATCAAACGGTTTTGGCCAATCTATTTGATCCAACCTGAAGGGCCGTACCCTATATGACAAGATTAGATGATGGTGGATGATCCACCGACAGAACATTAACGTCACGGGGGAAACCCCGGATACTAATGCCATGGGATGGTCCTCTACTTTCTTCACGAAGAACCTAGTTGCCGATGAATATCTACTTGCGCATGTAAAGATTAGAATAACATGTTTCGGGGTCCAACCTCATCGTGAACTAGTAGTGATTCCCTGTCGCACGTTATTACGCGGGGTGCCAAGCTACGCGTCGGCGTGCGATTGATATAGCCTGTCAGGCATACGGGTGGACTCACGGTCGCCGTGGATTCCCCAACCGCCCGAAGCGTATTGAATAGGCCCGGACTAGCTGTGGTACACGCTCTCGTGCCGCCGGGGCGGAGTGGTTAGATTTCAAAACGACACAAAGTGAGCGTTTACCAACTCTCGTAATCTTGCGGAATGAGTACCCTCAATGGTGAGCCCGAATTCGTACATTTAGGCGTCCGTGTATCATTGAAACGGTTAAAATCACCCCTATTGGTCAAAGAAAGCCATTCAGTCGTATAGCCTATAGTGTACCAGGGCATACTTGAAATGGACTTCTCTAAGGCTTCGGGGGAGGAAGGAGGTTTACTTCAATATCTTGGAGGGACTCTATAGTCCGATAGTAATAAGATTCTTCAAGTAACGTGGGGAAGTATGTATGGGCGGAGGAACCGTTATTCACTAGATCGAGTGCCGTATTGCAAGTACTACGCGGTGCCGACCGGCGTGGGCTGGATCTCAGACCGAAGACAATATTACGCCTCTGAGCATATGATGTCATTGTCTATCCGTCTTGGTGAGCGGGCTGGAGAATTAGGTCTGGCCACTTGGCAAGTAAGATGCTTAGGGAACATTCAAAAGTGTTCTGTAGCTGGTGATAAAGACATCGAAGGACTACTACTGTAGTTGTAA", "263 216 264 256");
        }

        private void DNA_Solve(string input, string answer) {
            var dnaString = DnaString.Parse(input);
            var result = dnaString.Sequence.PrintNucleotideCountsSummary();
            Assert.Equal(answer, result);
        }
        
        [Fact]
        public void RNA() {
            RNA_Solve("GATGGAACTTGACTACGTAAATT", "GAUGGAACUUGACUACGUAAAUU");
            RNA_Solve("CTCAGGCCAGCTGGTGCCACATTAAAACAGCCATGGGCATCAGTCCCCACTCCGGCGGAAGTTTAATATGGAAACAATCACTTGGACAGAATGCTAAGTTTCGTCAAGTCAACCCAATCGCGTCGAATAGTCGTATAAGGATACTACACGGTGCGTGACGAGACTCTGGTCTTCAGGTTGCGCATTGTCGGTATTGTGCGGCTGGACGTGCGCGCCTTGCTTATAATCGTGTGGGCTCGTAGAACGATTCACGATTCCCATTTAAGTCTTGGTCGCACTGTAACTGTAGTGCACAGCTTCGCTCTGGACTGCTTTGTTCAGATAAAGCGGCAATGCAGGTGCTCAAGCGCAGATATGGATGACGATCGTGGAGTTAATAGGCCATACAACGGACTAATGGCTAGAACCCGCTGGTCGATGGAGCCTGATCACCGTCTAAGCTTACGGTATTGGCGGGGATCACATCTGGGTAATCGCTGGCTATAGTGCGCGCCCTATCATCCACTTGCGGCCGTCATGGTAAATACGAATTGACTCAAGACGGCCGATACGCACAAGTGCACTAGAGCCGTGTCAGCCGACGGATACGGCTGTGATTGCGCCACATATCCTGTCCAGGCCGGTTCGGTGATTTACCAGATGGCTCTCGTCCACCCCCCTTGTACTCAAGCATGCTTCTCGCTACCCTGGCCGTTTAAGTATGGGGTTATTCATTGAGTCGCAGCAGAGCTTTACGCGGGCCCTACGTTGTATTGGGAGATGCTTGTCCGTCCCAGCTACCTACTGACCTGGGACCTTGAGCGGTAGTCGCGTCGTGACGCTCGGGCTCAGGGATAACATTCCTACCTACGGTCGTCGCTGAATCTAAAGACTGTCCTGCAGCCGGCGTGGGAAAACCGGCGGCCAAGCGACTACTGACATCGTATGTTTGGGGGTA", "CUCAGGCCAGCUGGUGCCACAUUAAAACAGCCAUGGGCAUCAGUCCCCACUCCGGCGGAAGUUUAAUAUGGAAACAAUCACUUGGACAGAAUGCUAAGUUUCGUCAAGUCAACCCAAUCGCGUCGAAUAGUCGUAUAAGGAUACUACACGGUGCGUGACGAGACUCUGGUCUUCAGGUUGCGCAUUGUCGGUAUUGUGCGGCUGGACGUGCGCGCCUUGCUUAUAAUCGUGUGGGCUCGUAGAACGAUUCACGAUUCCCAUUUAAGUCUUGGUCGCACUGUAACUGUAGUGCACAGCUUCGCUCUGGACUGCUUUGUUCAGAUAAAGCGGCAAUGCAGGUGCUCAAGCGCAGAUAUGGAUGACGAUCGUGGAGUUAAUAGGCCAUACAACGGACUAAUGGCUAGAACCCGCUGGUCGAUGGAGCCUGAUCACCGUCUAAGCUUACGGUAUUGGCGGGGAUCACAUCUGGGUAAUCGCUGGCUAUAGUGCGCGCCCUAUCAUCCACUUGCGGCCGUCAUGGUAAAUACGAAUUGACUCAAGACGGCCGAUACGCACAAGUGCACUAGAGCCGUGUCAGCCGACGGAUACGGCUGUGAUUGCGCCACAUAUCCUGUCCAGGCCGGUUCGGUGAUUUACCAGAUGGCUCUCGUCCACCCCCCUUGUACUCAAGCAUGCUUCUCGCUACCCUGGCCGUUUAAGUAUGGGGUUAUUCAUUGAGUCGCAGCAGAGCUUUACGCGGGCCCUACGUUGUAUUGGGAGAUGCUUGUCCGUCCCAGCUACCUACUGACCUGGGACCUUGAGCGGUAGUCGCGUCGUGACGCUCGGGCUCAGGGAUAACAUUCCUACCUACGGUCGUCGCUGAAUCUAAAGACUGUCCUGCAGCCGGCGUGGGAAAACCGGCGGCCAAGCGACUACUGACAUCGUAUGUUUGGGGGUA");
        }

        private void RNA_Solve(string input, string answer) {
            var dnaString = DnaString.Parse(input);
            var result = dnaString.ToRnaString().Sequence.ToString();
            Assert.Equal(answer, result);
        }

        [Fact]
        public void REVC() {
            REVC_Solve("AAAACCCGGT", "ACCGGGTTTT");
            REVC_Solve("TCTCGATGAATGTTAACTTTGCATCCCGGTCGTACCTGCACTCACACTGATCTCATTTAAATCGCCATTAACCCTGTTCCCGAATCAAAGGGAATATTTTATAAATATTTGGTGTCTCCCACAAACCCCCCTGCCGCACACGATGATTCTGTGCAAGGCAGACCGGCAATGGAGGCCTGTCAGTCCATGCGCCGCCCTGTGTGCACGATAGACAGATTGATCCGCCCTTGTTGTATGCGTCGTTACTGGTTCACGCCTTTCTGTCAAACGCCGTGTCAAACACGTATGTATCCGACAAGGGCCAGATTTTTGCCTCTGATCTTGACTGTGGAACCAACAATCACGGGCCCCATGTTATTTGTGGTGAAACTATCTGACGGGCTCTCCGGTCGGCCGCCAGGTTAAAGGCACCTTCGAGAACAGCTGCGGGGTGGTCACAGTGCAAGATCTACTAGCAACATGCACTCGTGTCACAAACAACCTACTTACCCTTAGCCGACTCCTCTTGTAATGATCCCGTATTCCGGCAATTCCTGTTCGACTCAAAGCACTGCCGGTAGTTCTTAACGGAGTTTGGGAGTGGCAGTATCCTTGGGAGGCTGTCCCTCCTAGAGTCCAACGATTTTGTCTACCACAATACGTAACCGCGAATCATAAGATTTGTACCGCCGCAAAATCCCGAGTATTCAATTAAAAGCGCGCTAAGTATTACTGATATGTCGCATGCCGACGTCTGATGTCATAACTGACCAAACGTCGCGTAGGTAGGGAAACAATAGACTCAACAACTGGGGAAGAGGTGTAGGTGCATAAGTACCTTGTCTCGCTTGACAGGCAGCGTCAGCAGGGTGTTATTGT", "ACAATAACACCCTGCTGACGCTGCCTGTCAAGCGAGACAAGGTACTTATGCACCTACACCTCTTCCCCAGTTGTTGAGTCTATTGTTTCCCTACCTACGCGACGTTTGGTCAGTTATGACATCAGACGTCGGCATGCGACATATCAGTAATACTTAGCGCGCTTTTAATTGAATACTCGGGATTTTGCGGCGGTACAAATCTTATGATTCGCGGTTACGTATTGTGGTAGACAAAATCGTTGGACTCTAGGAGGGACAGCCTCCCAAGGATACTGCCACTCCCAAACTCCGTTAAGAACTACCGGCAGTGCTTTGAGTCGAACAGGAATTGCCGGAATACGGGATCATTACAAGAGGAGTCGGCTAAGGGTAAGTAGGTTGTTTGTGACACGAGTGCATGTTGCTAGTAGATCTTGCACTGTGACCACCCCGCAGCTGTTCTCGAAGGTGCCTTTAACCTGGCGGCCGACCGGAGAGCCCGTCAGATAGTTTCACCACAAATAACATGGGGCCCGTGATTGTTGGTTCCACAGTCAAGATCAGAGGCAAAAATCTGGCCCTTGTCGGATACATACGTGTTTGACACGGCGTTTGACAGAAAGGCGTGAACCAGTAACGACGCATACAACAAGGGCGGATCAATCTGTCTATCGTGCACACAGGGCGGCGCATGGACTGACAGGCCTCCATTGCCGGTCTGCCTTGCACAGAATCATCGTGTGCGGCAGGGGGGTTTGTGGGAGACACCAAATATTTATAAAATATTCCCTTTGATTCGGGAACAGGGTTAATGGCGATTTAAATGAGATCAGTGTGAGTGCAGGTACGACCGGGATGCAAAGTTAACATTCATCGAGA");
        }

        private void REVC_Solve(string input, string answer) {
            var dnaString = DnaString.Parse(input);
            var result = dnaString.Sequence.ReverseComplement.ToString();
            Assert.Equal(answer, result);
        }

        [Fact]
        public void FIB() {
            FIB_Solve("5 3", 19, 1);
            FIB_Solve("9 3", 508, 1);
            FIB_Solve("32 3", 108412748857, 1);
            FIB_Solve("34 4", 18788331166609, 1);
            FIB_Solve("33 5", 112316396483406, 1);
        }

        private void FIB_Solve(string input, long answer, int start) {
            var n = int.Parse(input.Split(' ')[0]);
            var k = int.Parse(input.Split(' ')[1]);
            var result = Fibonacci.Solve(n, k, start);
            Assert.Equal(answer, result);
        }

        [Fact]
        public void GC() {
            GC_Solve(
@">Rosalind_6404
CCTGCGGAAGATCGGCACTAGAATAGCCAGAACCGTTTCTCTGAGGCTTCCGGCCTTCCC
TCCCACTAATAATTCTGAGG
>Rosalind_5959
CCATCGGTAGCGCATCCTTAGTCCAATTAAGTCCCTATCCAGGCGCTCCGCCGAAGGTCT
ATATCCATTTGTCAGCAGACACGC
>Rosalind_0808
CCACCCTCGTGGTATGGCTAGGCATTCAGGAACCGGAGAACGCTTCAGACCAGCCCGGAC
TGGGAACCTGCGGGCAGTAGGTGGAAT",
@"Rosalind_0808
60.919540");
            GC_Solve(
@">Rosalind_2144
CTTACGAATGAAGTTTGAGATGGGCTAAAAGACAGACCCATTGTCCAGGATAGACAGGTG
CAGTGCATGCGCCCTCCCGCATTGGCAGAATGTCTGCGAAGTACCGGTGTAGATAAATCT
CATTGATTACTAATTCCTTTCCTATGATATGGATAGTCCGGCCCACCCCCCCATAACGCT
CCGAGATGCATCCTAATGCTCTAAAGGCGGTCAAGACCGCGAGGGTACTCACAGTCTCCG
AGTAGTCATCTTTAGACGGGTGACTCGTATTGTACAATACTTACCGCAACAGTCCCAAGG
GCATGGACACCGGTGTCCAAGACCAGCACCTAGCAAAGTTTCCATGAATATCCTGTCGAA
GGATGTTATATGTCTCAATCGTCAAGTATACCGCTCCGGCGATTAAGGCGTGCAGCATTT
GGAAGGGAACAAAATCCACCACTTTTCAGCCTCTCGATACGCGCGGATAGGAGGCGCGGA
CATGTAAGCGTAGGAAAAGAAGCTCAAGATCGGGCGGAAGGCAGTGGAGAGCACTGCTTG
GTCCTGGTTCCTGCTAGCCAAGAACGGCACAACCTTTACAGGGCTGACGCGCAGGGACGC
TTCTCAGATGATCGTCCACAAATTGCTACTAGCTGTACAGCTTTGGGTAAGTTCCTGGCT
ATGGGCTACACGGCCCCATCGGGCAAGGGGTGTATAAGATCTGCCCTGCAACCTGTCCGC
AGTAGTCTTTGGACCGCAATGTTTGTACGGACAGGGTCTTAGATACGCCGTTGGCGATAA
TAGCAACACGCTAGACGTACTATCGAGGATGCGGCCAACTCCTCCACAAGTGGTTGCTTC
TCCGGACGCGATCACATAGAGCTATCAACGGCCCCCATTCGTGGACGGAGATCCAGTCCC
TATCCTGAGCTCTTATCATTACTGAATGAAACCGAAGTAAAGTTGGAGCGAGACTTGCAT
CCTACCCGGGAGACGCCTGCACGCGCGTC
>Rosalind_9559
GAGAGATGTGGCCACAGACTCTCGCCGACACACTTATTTCTGCTTCTAGCTCCATACGTA
TTCTTTTGCGTGACAATCGATGCCTTTGCCCCAGAGCACCCACATTCGCTACCCCCCACG
CACCGCACTGCTCTGACGCGAAGGGGCAATGGCGAACCTCCGGTGTATATTTGAACTCGA
GCGGTTGCTAAACCATGACATTAGCTTACATCCCAAGTTACAACTGTGCTGGAAAATTTC
TCATTTTTAAGGCTTATCACTCTAGGCATAAATACCCGCACTGCAGTATCTGACCCCGGC
TGCCCCATTTCGCCCTCGACAACATAAGGATAACCAACGAGGCCAAGAAACAAATACGCG
TCTGTAGATATGAAACCAGCTCTTAGGCGAGGTATGACTCTGACGGTGCGGGAATTCATG
TATGGATGTGGTCGTAACTGTGTAGGGGAGCCAGTTCGCGATCGGAGCAAGTCACATACA
GCTTTTAGTGATATGCCCCAGGATCTCCAAACGGAATATGTCTGCGACCTCACGCCATAA
TCCTGACTGCTCTAGCTGCTCTTGTAAAGATGAAGTTGCACGGCCGCGAGCTGGATATGC
TGCAATTCTTCTCAGCTTCCTTACTCGTTCGGTCGCTCAATATGTGTAACGCCACCATAC
ACTAAGCGACGGGAGCACAGCGGGTGACTTGACTCACTCTATTGTTAGCTGCCCAAACAG
TTTTGTGGAGATCCGGATCACGTGAGTTTATCCGCCCGTTCACCTTTTGGCCTGCAGTGT
TAGTAACCTCCAGCTCAATTGAAACGGGACCGTTAGATGCCTCATTACGGCCCAGCTCGT
AACTGACTCGTAACAGACAACACCCTGTTTGTCCAAACATCTGATATCTATTGCCCTGGA
TTCGTCTATCGTGTACACTAAGGCCTATCCGTTAAACATGTCACGACGCCCTAGCATTAC
TGAGCGATTTGCAGGCCAAATGGTATAATCTCACGCA
>Rosalind_5219
AATACATACCTACCGGCAAAGAGAATCTCACGTCACAGCTTGCACGATCCAGCTTATTTC
TGATTAGGTAGCGCTACTACGTTGGGGATCGGACCCCCTGCCATTTCACATCAACGCCCA
TCTCACTGTTCCCGGTTGACCAATGGATAGACGAGACTGCATGGGGGTAAGTAAACGGTA
TCATCCAAGACGGTGGACTGGTGTTCTCAGAATCCAATAATTGATTTCTAAAAAATATCC
ACCAAGTGGTAGCTGTGGACTTAGTGGCTACTAACGTCCTCTAGATTTTTCTGTAAGTTA
CCGCAGCAGGCCATACCCCTTGGTAAGTAGATCAAAGCGCGAAATAGAGTCGCCCGACAA
CGCCCCGGAGTAGTGTATTCATGAGCCTTTCGATTGGTAGCTGAATCAGAGAATCATCCT
GAAACGCAATAACACCCCAGAAAAGGGTTCGGAGATAGGAAATTATGGCGCCACGGAACG
ACCGAGGTTGGACCGTTGGTTTCTACTGTTTGGCACGGCCATTGATTGTGCATCTTAAAC
GTAGTAAGGACGACGTTCATATCGCGGTGCGGCGCGGTTGTTGAACATCGAGGATATCGA
ATGCTTAGGGATCCAAGGTAGTCCGGAGGAGAACGGACGGGGCTTTCTGGCATCGTACTC
AGGGCTCGAATTACAGAAGGAGGTAGCTTCAGCAGGGCTAACTCAGACTACTTATCTATG
ACAGTCCCCCATGTATCGGTGATCTCAATGGGACTAGGGTTAACGTCTGTGGAAAATACG
GGCCATAAAAAACTTCGCATGTCTCACTGCAGGCGTCGGAAGTTGTGTGGAGCGAACCCA
TCGTAAGTGACAGGGAACTTGCCGCGACTAATAACGGGTAGGGGAGTATAC
>Rosalind_1151
GGATCGTTTCGGTTGATAAGCGTAATGCAGGTGTTGGACCATTAACCTGGGTCCCACGGT
GTTCGTAAACTATTGTAGGAAACAAGACCTTGTTTTATAAGGATCCGGTCACTAAACCTT
ACCAGTTAGCCAAGTTGCCAATAAATATTACTCCAGGGCTATAATGTGTTGCCTACAGCC
CCCAAATGCTAGCGATGAGGCTCCCTATAATCTCTCTAAAGGCGTAATTCCGGACTGCAT
ATGACGTATGACGTCTGTGAGCGAATTCCTGCTGCCTTAAAGCTTTGGCGGTTGTGGATA
AAGTTGCCGAGGCGCCCACAAATTTCAGGTGAGCGCACCTTGTTCTTAGGGCCATCTGTG
GTGCCGAAGGACAAAAACACACGTCGTACTGTTATCCTGCAGTACAAGATATTGAGCATA
CTCGAGAAGCCCTGACGGCCTTCCTCTTGCCAAATGATCATTAATGACGGAGTTGCGGCG
CGCCGAACTAAATTCTCTGTACTGCCAGTAAGCGGGAGAACGGGAAGGATATTCCTGTCT
GGTATGGTTTACCCTAGGCAGTTGGGCTTTTTCGATGTGAGTGGTCCACCATAAGCTTAC
CACGCTAGCCCCGGTCCCCAGACTTGTTTATAAATGCGCATTCCGCTGCACGTGTAATCG
CTGCACGTCCTCGTAAGGTCCAATCCCCGCACTCTTAATCGACTGGACTAGAGGGAATTC
ACCCGATGGGTCCGGGTCTCCTAAGAGTGATCCATCACACGCGTTAGATGTGCAAAGTGT
AGACCATAATTGGCAATTCTGGGTAAGGTATAGTGCGGATCATCAAAATCTGTACGAAAG
CGTCGAGTCCTTAATAATCTGTTGGACGTTAGGAGAAAATCTCCGAAAATCCGAATCACT
CTCGACATTGTACAAAAC
>Rosalind_1054
CTGGTTCTATTTCCTATCAGAGTTCAGCTTGGTACTAGAGATATTCGGCTACCGACCCTT
AACTCTTCCTAGACTGCCAGTTATTCCCGTAGAGCATTACACTGCACTATTGGTCGCCCG
ACGTTCTCCATAGGCAAAGCGCGGTAGCGATCCCCCAAGGCACGGGCAGTAGGCGCAACC
GGTAAATTGGTCTATTATTACAAGGGATACAGGGCCTTAAGCATTCCGAAAATCCAAAAT
GGGCTCACAGTGATGGAGGGATCTCCATTTGAGTGTTAACTGTGTTAGCACTCCTTTCAC
CTAAAAGCTTGACCATGGAGCCTAAAAAGATGGACATTGCCTGGCTACAGACTCGAACTA
TCAGCCCCGCGTGTGACGCGGTATTTCACCTTCCTTTCGCGGACGATAATCGCTAAGAGA
GAGTACGACTTATATACCAACTGTCCTATGGTGCTTAACGTCATCCCCCCCGCTAGGTCT
AGAATAAGGGGATCCGGCCTCCCAGGAACGTCGTTCAAACATTAACAGACGGGCGTTCGG
ATTGACATGGGAACGACCAGTTACTAATAAGTTGCCGCGCAACCTGCCATAACTTGCATG
GGAGCGATTATAGGCTAAATCAAGCTCATCAGCGTATCCCTCGAGCGGGTCTACGTATAT
TATCGTGGGATTTTCCCATCCGCTATACGATGTTATTGGTGCTGAGATGCTCGGTTTCTG
TGTACGACTCCATGTAACACGTCTGGAACCAGTAATGAACGTTCCATCTGTATAACGGTA
GCCTGCTTCGATATTAGATGTACGTGTAACATTGCGGTGCGACAAATGGCGCCAGCATGT
GAGTGTGTGTT",
@"Rosalind_2144
52.173913");
        }

        private void GC_Solve(string databaseString, string answer) {
            var database = Database.Parse(databaseString);
            var highest = database.Values
                .OrderByDescending(n => n.Sequence.GcContent)
                .First();
            var result = string.Format("{0}\r\n{1:N6}", highest.Label, highest.Sequence.GcContent);
            Assert.Equal(answer, result);
        }

        [Fact]
        public void HAMM() {
            HAMM_Solve("GAGCCTACTAACGGGAT", "CATCGTAATGACGGCCT", 7);
            HAMM_Solve("CGAAGCCCTAAACGGAGAAGCCGCCGTATATGTAAACGCTGTGTTACAACGAGGGTTGTCTTCCGTAATAACCTGGATGCTGCACGCTTTCCCAAGACCCTCCATTATCATGGAAATAGCAACTCACTGGCCACGGTAAAATAAGTCTCCAGCGCGTTTAGCAGAGATCCTTCAAGACGAGCGCGAGCAGTAAAGCAATGGTCGCGGGCCTTGTATTGGGCCGATTTGATGTATCCCCACGTCGTATTTACCCACTTCCCACTTCCCCTCAGGCTGCGGCGGGCCTTACCCGAGGGCTTTGTTACGGTGCCGGCGCAGAGCGGCCAGGAAGCAATCTAACTCCCTATGAAAGTGCCAGGTAATCTCTCTGTGGCACAGGTTAAAAGACTTTGTCGTCCTCTGTCGCGTCATATCGAAACTTGCAGGGGCGGTCAGTCGTCGCGGCCGAAGTTCTAAGTTAACTTCGACACCCTCGTCAATCGGCATTACGTTGCAGCCAAATAATTCCGACTCCCAGTCCTAAGCCGACCGTATTCGGCAGGTGTGGCCTGTCCCCCGGCTGGCGCTCTCTTTACACGAACGAAGGTACTCGTGTGAGACATAGAAAGGAGAGGGCAGACCGTGGTCCGCATTAATGCGGGTCGCAAAAGCCGACCTGCTATTAAGTTGCGTACTCGTTCCCGAAAATACTTGGCTACGTTACTAGCGGACGAAAAGCATCACAGAGATAGCCCTCGGTCTGCTGGGACATAAGATAGTTCGTACTCCTTTCTTAGGTATTTTGTCTTGGTACTTACCATCACCGCGGATATGCCACGCTCATGAAAATTCCCCGAACTTCCAGGTTCCACAGCAGATAACCAAGGCCGGGCGACGTTACTGCCTTTCTGCCCCCGACTAGAAGTGATAGGTCTGGGCATGAA", "GTACTCGGTAAACAGAGGACCGGCTGCGGGATTACGCGCTCCACATCACCCGGAATTGCCCACCGTGTTGACAAGGATGCGACAGTCTTTACTCAGATAGGGGCATACTATTGAGATAACAACGGGTAGGGCACGCTTTTGAAAGTGCAGAGTTGATGAGGCTGCGGGGTGCCACGCCGAACGCGTGTTATAACGGTTTCATCGAGGGGCTCGGAATCCGACGACAACTCTGCGGTGGATGTGGTGTGTAACCACTGCGCTCTCTCCCTGGGCCTCCGACGGTCGCAACCAGACAACAGCTATATGGTACGCACCTCGGGCGACCTGTAAATAACCAAACTGACTAAGGAAATAAAGCGTACACGCTTTATCGAACTGGGAAAGAGTTGTCTTCGCGCTTCGTTCCGTCATGACAACGTTGATAGGCACTGGTTACCTACACGGGCGGCGTACTAAGGTAACAACGAATGCCTCGGAGATGGGCATAATGAAAACTTCCCGCCGTCCTGGTACCCGGATCGTGGCCGACTTTCATTGGCCTCTGGGGCCTGATCTCTTGCGGCATTTCTAAGCAAGTGATCCATGGAACTTTTAGTAGACCTCGCAGCTAGCGAAGATCACGTGGTGCATATTAATGCTGACCGAAATCGACGGGCTTCCAGTAGTTTGGGTAGCCGTGCCGATCTGTATGGCACTTCGACTCCAGCCTTTACCGTAAAATGCAAAGACGCCCGTGGGCGAATTCGAATTTCAGAGCGTGCGTCTTCTTTTCTTAGGTGTTTTCTCTGTTGAGGTACCCCCACCTGGCGCTTACGACGGACACTATACTCCTCCGAAGATCGTGCCTAGTCACCAGCCCAACCAGCCCGCGTGGAGTATCTGCAAGTCGGCCCAGGATTTGACATGATGGGTCCCGTCTGGAA", 445);
        }

        private void HAMM_Solve(string a, string b, int answer) {
            var dnaStringA = DnaString.Parse(a);
            var dnaStringB = DnaString.Parse(b);
            var distance = dnaStringA.Sequence.CalculateHammingDistance(dnaStringB.Sequence);
            Assert.Equal(answer, distance);
        }

        [Fact]
        public void IPRB() {
            IPRB_Solve("2 2 2", "0.78333");
            IPRB_Solve("21 15 19", "0.77121");
        }

        private void IPRB_Solve(string input, string answer) {
            var factors = Factor.GeneratePopulation(input);
            var probability = 1 - Probability.ForSet(factors, f => f.Zygosity == Zygosity.HomozygousRecessive);
            var result = string.Format("{0:N5}", probability);
            Assert.Equal(answer, result);
        }
    }
}
